import Head from 'next/head'
import { Posts } from 'src/components/posts/posts';

import { Header } from '../components/Header'
import styles from '../styles/Home.module.css'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>index page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <Posts />
    </div>
  )
}
