import Head from 'next/head'

import { useInputArray } from 'src/hooks/useInputArray'

import { Footer } from '../components/Footer'
import { Header } from '../components/Header'
import { Main } from '../components/Main'

import styles from '../styles/Home.module.css'

export default function Home() {
  const [text, array, handleAdd, onChangeValue] = useInputArray();

  return (
    <div className={styles.container}>
      <Head>
        <title>index page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>

      <input type="text" value={text} onChange={onChangeValue}/>
      <button onClick={handleAdd}>追加</button>
      <ul>
        {array.map(item => {
          return (
            <li key={item}>{item}</li>
          )
        })}
      </ul>

      <Main page="index" />
      <Footer/>

    </div>
  )
}
