import { useRouter } from 'next/dist/client/router'
import Head from 'next/head'

import { Header } from 'src/components/Header'
import styles from 'src/styles/Home.module.css'


const PostId = () => {
    const router = useRouter();

    return (
        <div className={styles.container}>
            <Head>
                <title>index page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />

            <p>{router.query.id}</p>
        </div>
    )
}
export default PostId;
